### ISSUE TITLE
La hora de la creación del artículo no es la de Colombia

### ISSUE THREAD

**Issue by seraleman** [codigoc13/c13-app-back#32]

**Comment by seraleman** [comment]
@LozanoAndersonTheStain

**Comment by LozanoAndersonTheStain** [comment]
![image](https://user-images.githubusercontent.com/105325885/204063547-1cb23fb2-1e19-4b74-9cef-e0251ad571d4.png)

Solucionado

**Comment by seraleman** [comment]
Perfecto!

**Comment by seraleman** [comment]
Esto deberá manejarse en el código @LozanoAndersonTheStain @ValentinaMontoya

**Comment by seraleman** [comment]
Se soluciona
