### ISSUE TITLE
La hora de la creación del curso no es la de Colombia

### ISSUE THREAD

**Issue by seraleman** [codigoc13/c13-app-back#33]

**Comment by seraleman** [comment]
@Panditax0902

**Comment by Juanchos2905** [comment]
![image](https://user-images.githubusercontent.com/105325621/204065276-c3efd9b2-c71b-41b1-a616-bfefe938ffe1.png)

**Comment by seraleman** [comment]
Perfecto!

**Comment by seraleman** [comment]
Esto deberá manejarse en el código @Panditax0902 @MarisolMurillo

**Comment by seraleman** [comment]
Se soluciona
