### ISSUE TITLE
La hora de la creación de la cohorte no es la de Colombia

### ISSUE THREAD

**Issue by seraleman** [codigoc13/c13-app-back#34]

**Comment by seraleman** [comment]
@JordanRendon

**Comment by milenasandra** [comment]
![image](https://user-images.githubusercontent.com/105325805/204065442-e4ca84fa-09a3-4b9b-aa26-a163f7f5b310.png)

**Comment by seraleman** [comment]
Perfecto!

**Comment by seraleman** [comment]
Esto deberá manejarse en el código @milenasandra @JordanRendon

**Comment by seraleman** [comment]
Se soluciona
