### ISSUE TITLE
La hora de la creación de la carrera no es la de Colombia

### ISSUE THREAD

**Issue by seraleman** [codigoc13/c13-app-back#35]

**Comment by seraleman** [comment]
@DanielV96

**Comment by DanielV96** [comment]
![image](https://user-images.githubusercontent.com/105326240/204063749-51fabc4d-71fe-48c5-9d19-84b90081e615.png)

**Comment by seraleman** [comment]
Perfecto!

**Comment by seraleman** [comment]
Esto deberá manejarse en el código @DanielV96 @samuuelalv

**Comment by seraleman** [comment]
Se soluciona
